---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: flake8
spec:
  description: This task runs flake8 linting on the source code.
  workspaces:
    - name: source
  steps:
    - name: run-flake8
      image: python:3.9
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/sh
        set -e
        echo "Installing flake8..."
        pip install flake8
        echo "Running flake8 lint..."
        flake8 --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 --count --max-complexity=10 --max-line-length=127 --statistics
